server:
  port: 9999

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
#      routes:
#        - id: default_route
#          uri: http://www.baidu.com
#          predicates:
#            - Path=/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/

#eureka:
#  instance:
#    prefer-ip-address: true
#    hostname: ${spring.cloud.client.ip-address}
#    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
#  client:
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:8888/eureka/

logging:
  level:
    org.springframework.cloud.gateway: debug




