spring:
  redis:
    host: 127.0.0.1
    port: 6379
#    Redis 数据库索引（默认为0）
    database: 0
    jedis:
      pool:
#        连接数最大连接数
        max-active: 8
#        连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 3000
#        连接池中的最大空闲连接
        max-idle: 20
#        连接池中的最小空闲连接
        min-idle: 2
#        连接超时时间（毫秒）
    connect-timeout: 30000
