spring:
  redis:
    cluster:
#      设置key的生存时间，当key过期时，它会被自动删除
      expire-seconds: 120
#      设置redis集群的节点信息，其中namenode为域名解析，通过解析域名来获取相应的地址
      nodes: 66.0.17.174:7001,66.0.17.43:7001,66.0.17.35:7001,66.0.17.214:7001,66.0.17.51:7001,66.0.17.126:7001
    password: admin@123
#     连接超时时间
    timeout: 5000
#    读取数据超时时间
    so-timeout: 5000
#    最大尝试次数
    max-attempts: 10
    commandTimeout: 5000
    pool:
#      连接池最大连接数（使用负值表示没有限制）
      max-active: -1
#      连接池最大阻塞等待时间
      max-wait: -1
#      连接池中的最大空闲连接
      max-idle: 8
#      连接池中的最小空闲连接
      min-idle: 0


