spring:
  datasource:
    name: mysql
    url: jdbc:mysql://66.0.17.219:3323/HOTDB
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
